### ISSUE TITLE
Popover breaks on pjax reload

### ISSUE THREAD

**Issue by caioh** [kartik-v/yii2-popover-x#11]
Hello,
I have a paginated gridview and every page contains 10 detailviews with two popovers that trigger ajax actions.
When I change the page the popover brakes and I cannot find a way to reinitialize it automatically or to change the initialization with event delegation. I must reload the entire page to reintialize it but I'd like to avoid it.

Thanks in advance for any help.

**Comment by Albitos** [comment]
I experience exactly the same problem - popover does not work after pjax reload.

**Comment by Commifreak** [comment]
Exactly the same, Yii 2.0.12.

**Comment by kartik-v** [comment]
With PJAX, You are overwriting the HTML markup that will obviously erase all previous javascript/jquery bindings and break all javascript that were associated with the old markup / buttons/ content that triggered the popover. 

Hence you need to write your own javascript code correctly to reinitialize any plugins based on your pjax reload events.

For javascript coding, you can go through the [popover button plugin options docs](http://plugins.krajee.com/popover-x#popover-button-options) and try to initialize the popover button on the element after your pjax reload event that should trigger the popover.
