### ISSUE TITLE
Error after bootstrap updated to 3.3.4

### ISSUE THREAD

**Issue by SDKiller** [kartik-v/yii2-popover-x#6]
Dimiss button does not work

**Comment by kartik-v** [comment]
Not tested for bootstrap 3.3.4... yet... will suggest to hold.

**Comment by kartik-v** [comment]
Resolved via [bootstrap-popover-x upgrade to release v1.4.1](https://github.com/kartik-v/bootstrap-popover-x/releases/tag/v1.4.1)
