### ISSUE TITLE
kartik-v/yii2-popover-x closeButton not working

### ISSUE THREAD

**Issue by fwroman** [kartik-v/yii2-popover-x#7]
Hi, I'm using kartik-v/yii2-popover-x, and closebutton not hide the dialog popoverX when I cick it.. I actually don't know what's the problem..

Hope someone could help me, thanks

**Comment by kartik-v** [comment]
You need to ensure you have the updated release of the extension by updating packages via composer and cross checking here the js files are same. After update, you also need to ensure that your browser cache is cleared, you have removed your yii web runtime assets, and restarted your browsers.

**Comment by fwroman** [comment]
Thanks for your answer, I'm going to install the extension again and do what you recommended me

**Comment by fwroman** [comment]
I did what you said and the widget is working fine now :).... thank you so much
