### ISSUE TITLE
Inactivated when used in gridview toolbar and pjax is used for pagination

### ISSUE THREAD

**Issue by pgodiani** [kartik-v/yii2-popover-x#8]
I tried to place this widget in the k-gridview toolbar
When the page containing the grid is first displayed, the popover works fine
However, switching to another grid view page (pjax is used for pagination) seems to inactivate the 
widget.
Pushing the button does nothing.
Forcing complete refresh of the page restores functionality

**Comment by kartik-v** [comment]
You need to reinitialize jquery plugins after pjax reload.

As a generic rule you need to understand that PJAX overwrites the HTML DOM... it does not trigger javascript functions or plugin codes that may be used in your content.

Within your pjax container any widgets that use jquery plugin functionality will not automatically trigger the jquery call that renders the widget. You need to do this manually.

**Comment by sharrito1973** [comment]
Could write a example as reinitialize jquery plugins after pjax reload?
Thanks a lot!!!

**Comment by lkossis** [comment]
Just in case anyone else runs into this, in my view (which contains the pjax call, I added:

`$this->registerJsFile('/js/init-popover-x.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
`
and then I copy-pasted part of bootstrap-popover-x.js, which by observing the code I found out does the popover-x stuff, namely that part which seemed like it was triggering the related elements:

`$(document).on('pjax:end', function() {
    $("[data-toggle='popover-x']").on('click', function (e) {
        var $this = $(this), href = $this.attr('href'),
            $dialog = $($this.attr('data-target') || (href && href.replace(/.*(?=#[^\s]+$)/, ''))), //strip for ie7
            option = $dialog.data('popover-x') ? 'toggle' : $.extend({remote: !/#/.test(href) && href},
                $dialog.data(), $this.data());
        e.preventDefault();
        $dialog.trigger('click.target.popoverX');
        if (option !== 'toggle') {
            option.$target = $this;
            $dialog
                .popoverX(option)
                .popoverX('show')
                .on('hide', function () {
                    $this.focus();
                });
        }
        else {
            $dialog
                .popoverX(option)
                .on('hide', function () {
                    $this.focus();
                });
        }
    });
    $('[data-toggle="popover-x"]').on('keyup', function (e) {
        var $this = $(this), href = $this.attr('href'),
            $dialog = $($this.attr('data-target') || (href && href.replace(/.*(?=#[^\s]+$)/, ''))); //strip for ie7
        if ($dialog && e.which === 27) {
            $dialog.trigger('keyup.target.popoverX');
            $dialog.popoverX('hide');
        }
    });
});`

Note that the code from Kartik's script is enclosed in a 

`$(document).on('pjax:end', function()`

bracket which I found [here](https://github.com/defunkt/jquery-pjax/issues/560)

Hope it helps someone

**Comment by jmper** [comment]
@lkossis I had the same issue and while your code does work, here's much simpler solution (based of course on what I found in bootstrap-popover-x.js):
```javascript
$(document).on('pjax:end', function () {
    var $btns = $("[data-toggle='popover-x']");
    if ($btns.length) {
        $btns.popoverButton();
    }
 });
`

**Comment by lkossis** [comment]
@jmper Thanks for that, always keen for more knowledgeable, succinct solutions to problems..

**Comment by Jonyx4** [comment]
@jmper excellent workaround, I added like this to yii2 and php code ->

`<?php 
$this->registerJs(
        '$(document).on("pjax:end", function() {              
                var btns = $("[data-toggle=\'popover-x\']");
                if (btns.length) {
                    btns.popoverButton();
                }
            });
        ');
?>`

**Comment by kartik-v** [comment]
Yes that is the way to reinitialize popover-x plugin.

**Comment by i-internet** [comment]
> <?php $this->registerJs( '$(document).on("pjax:end", function() { var btns = $("[data-toggle=\'popover-x\']"); if (btns.length) { btns.popoverButton(); } }); '); ?>

Thank you so much

**Comment by lromanut** [comment]
Hi! 
I am rendering a gridview (Kartik) with renderAjax after using a form. The gridview is rendered on top of the same view where the form is located. Now: the export function works but the table pagination reloads the page. Can anybody help me.?

**Comment by neoacevedo** [comment]
> @jmper excellent workaround, I added like this to yii2 and php code ->
> 
> `<?php $this->registerJs( '$(document).on("pjax:end", function() { var btns = $("[data-toggle=\'popover-x\']"); if (btns.length) { btns.popoverButton(); } }); '); ?>`

Currently I have that code in the view having the GridView but when I use the paginator with pjax, it simply doesn't work because I click on any editable cell and the popover isn't fired so I have to reload the page.

**Comment by jmper** [comment]
> Currently I have that code in the view having the GridView but when I use the paginator with pjax, it simply doesn't work because I click on any editable cell and the popover isn't fired so I have to reload the page.

It should work. Check in browser's console whether you have any JS errors.
